version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/usr/src/app
    environment:
      - NODE_ENV=development

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
